name: flutter_chat
description: >
  A full-featured (simple message, multimedia message, voice, video)
  flutter chat application by SignalR and WebRTC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  built_collection: ^5.0.0-nullsafety.0
  built_value: ^8.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.1
  bloc: ^7.0.0-nullsafety.1
  flutter_bloc: ^7.0.0-nullsafety.1
  shared_preferences: '>=0.5.10 <2.0.0'
  url_launcher: ^6.0.0-nullsafety.6
  signalr_core: ^1.0.8
  device_info: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: any
  pedantic: ^1.10.0-nullsafety.3

dependency_overrides:
  equatable: ^2.0.0-nullsafety.1

flutter:
  uses-material-design: true
