name: flutter_chat
description: >
  A full-featured (simple message, multimedia message, voice, video)
  flutter chat application by SignalR and WebRTC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  built_collection: ^5.0.0
  built_value: ^8.0.2
  equatable: ^2.0.0
  bloc: ^7.0.0-nullsafety.2
  flutter_bloc: ^7.0.0-nullsafety.2
  shared_preferences: ^2.0.4
  url_launcher: ^6.0.1
  signalr_core: ^1.0.8
  device_info: ^2.0.0
#  flutter_webrtc: ^0.5.8
  flutter_webrtc:
    git: https://github.com/flutter-webrtc/flutter-webrtc

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  built_value_generator: any
  pedantic: any

dependency_overrides:
  equatable: ^2.0.0
  meta: ^1.3.0

flutter:
  uses-material-design: true
